#in prod deploy change localhost variable
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carniceria?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    smtp-port: 587
    username: darioegb@gmail.com
    password: dari0bass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8080
  address: localhost
  